version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gulp-jshint
    versions:
    - 1.12.0
  - dependency-name: gulp-filter
    versions:
    - 6.0.0
